spring:
  application:
    name: order
  datasource:
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.215.147.110:3306/yangk?characterEncoding=utf-8&useSSL=false
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
  jpa:
    show-sql: true
server:
  port: 8773
#  servlet:
#    context-path: /
eureka:
  client:
    availability-zones:
      default-Zone: http://localhost:8761/eureka

ribbon:
  ReadTimeout: 5000
  SocketTimeout: 5000
