spring:
  datasource:
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.215.147.110:3306/yangk?characterEncoding=utf-8&useSSL=false
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
#      spring.datasource.hikari.connection-test-query: SELECT 1
  jpa:
    show-sql: true

server:
  port: 8772
  
boy: 
  name: zhangsan1
